<?php namespace JF;
/**

Copyright 2017 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-36971c
Date:    2017-10-19 09:37:51
Version: v2.0.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-36971c",
    "email": {
        "to": "support@pettycash.com.ng",
        "cc": "",
        "bcc": "",
        "subject": "Company membership form",
        "template": ""
    },
    "admin": {
        "users": "admin:6c1dd",
        "dataDelivery": "emailAndFile",
        "save2dbExample": true
    },
    "thankyou": {
        "url": "https:\/\/www.pettycash.com.ng\/investment.html",
        "message": "",
        "seconds": "30"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "Company Name",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "max": {
                        "enabled": false,
                        "val": ""
                    },
                    "min": {
                        "enabled": false,
                        "val": ""
                    },
                    "minlength": {
                        "enabled": true,
                        "val": "1"
                    },
                    "maxlength": {
                        "enabled": true,
                        "val": "40"
                    }
                }
            },
            "id": "f9",
            "cid": "c53"
        },
        {
            "label": "Contact Person",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "max": {
                        "enabled": false,
                        "val": ""
                    },
                    "min": {
                        "enabled": false,
                        "val": ""
                    },
                    "minlength": {
                        "enabled": true,
                        "val": "1"
                    },
                    "maxlength": {
                        "enabled": true,
                        "val": "40"
                    }
                }
            },
            "id": "f4",
            "cid": "c26"
        },
        {
            "label": "Contat Person Email",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": false,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "minlength": {
                        "enabled": true,
                        "val": "3"
                    },
                    "maxlength": {
                        "enabled": true
                    }
                }
            },
            "id": "f10",
            "cid": "c64"
        },
        {
            "label": "Contact Person Phone number",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "max": {
                        "enabled": false,
                        "val": ""
                    },
                    "min": {
                        "enabled": false,
                        "val": ""
                    },
                    "minlength": {
                        "enabled": true,
                        "val": "5"
                    },
                    "maxlength": {
                        "enabled": true,
                        "val": "14"
                    }
                }
            },
            "id": "f6",
            "cid": "c36"
        },
        {
            "label": "No of Employees",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1-10",
                        "checked": false
                    },
                    {
                        "label": "11-50",
                        "checked": false
                    },
                    {
                        "label": "51-200",
                        "checked": false
                    },
                    {
                        "label": "201-1000",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "1000+",
                        "value": null,
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f8",
            "cid": "c46"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ]
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class